### ISSUE TITLE
Updated?

### ISSUE THREAD

**Issue by DjustinK** [kstep/ajenti-transmission#1]
Does this plugin still gets updated? Got he plugin working but it crashes alot.

**Comment by kstep** [comment]
I use this plugin all the time on my server. My setup is single server with Transmission daemon running 24/7 on the same server as Ajenti with the plugin, listening on 127.0.0.1:9091, and it works for me.

I'm pleased to know it is useful for someone else. If it crashes for you, please provide the following information:
1. error traceback,
2. what ip/port your transmission-daemon is listening,
3. does ajenti run on the same machine as transmission-daemon,
4. also make sure some firewall (like iptables) doesn't block connections to transmission-daemon.

I have my full-time job, so I don't promise I will fix everything in a moment, but I'll try to look into it once I have some spare time. Please understand, this is an open-source project and I don't get paid for it, I do it to entertain myself and because it is useful for me, but I can't support it 24/7.

As this issue is not an actual issue, I close it now. If you have any concrete issues, please create new ones. Thank you for understanding.
